/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6aqO92RwrXM
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

 import { Libre_Franklin } from 'next/font/google'
 import { Arimo } from 'next/font/google'

 libre_franklin({
 subsets: ['latin'],
 display: 'swap',
 })

 arimo({
 subsets: ['latin'],
 display: 'swap',
 })

 To read more about using these font, please visit the Next.js documentation:
 - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
 - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
 **/
import Link from "next/link"
import {Label} from "@/components/ui/label"
import {Input} from "@/components/ui/input"
import {Button} from "@/components/ui/button"

export default function autorization() {
    return (
        <div>
            <header className="bg-primary text-primary-foreground py-4 px-6">
                <div className="container mx-auto flex justify-between items-center">
                    <Link href="#" className="text-2xl font-bold" prefetch={false}>
                        Car Rental
                    </Link>
                    <nav>
                        <ul className="flex space-x-4">
                            <li>
                                <Link href="/main" prefetch={false}>
                                    Каталог
                                </Link>
                            </li>
                            <li>
                                <Link href="/contact" prefetch={false}>
                                    О нас
                                </Link>
                            </li>
                            <li>
                                <Link href="/contact" prefetch={false}>
                                    Контакты
                                </Link>
                            </li>
                        </ul>
                    </nav>
                </div>
            </header>
            <main>
                <section className="bg-white py-24 px-6">
                    <div className="container mx-auto max-w-md">
                        <h1 className="text-4xl font-bold mb-4 text-center">Авторизация</h1>
                        <form className="space-y-4">
                            <div>
                                <Label htmlFor="email">Email</Label>
                                <Input id="email" type="email" placeholder="Введите email"/>
                            </div>
                            <div>
                                <Label htmlFor="password">Пароль</Label>
                                <Input id="password" type="password" placeholder="Введите пароль"/>
                            </div>
                            <Button type="submit" className="w-full">
                                Войти
                            </Button>
                            <div className="text-center">
                                <Link href="/registration" className="text-primary hover:underline" prefetch={false}>
                                    Нет аккаунта? Зарегистрироваться
                                </Link>
                            </div>
                        </form>
                    </div>
                </section>
                <footer className="bg-primary text-primary-foreground py-4 px-6">
                    <div className="container mx-auto flex justify-between items-center">
                        <p>&copy; 2023 Car Rental. Все права защищены.</p>
                        <nav>
                            <ul className="flex space-x-4">
                                <li>
                                    <Link href="#" prefetch={false}>
                                        Условия использования
                                    </Link>
                                </li>
                                <li>
                                    <Link href="#" prefetch={false}>
                                        Политика конфиденциальности
                                    </Link>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </footer>
            </main>
        </div>
    )
}
